## 人物客制化以加强区分度
define lyh = Character("梁易寒")
define sm = Character("沈明")
define yc = Character("应潮")
define hzy = Character("胡正阳")
define 应响 = Character("应响")
define yx = Character("应晓")
## 路人
define teacher = Character("教师")
define assistant = Character("助教")
define girl = Character("女生")
define boy = Character("男生")
define studentA = Character("学生A")
define studentB = Character("学生B")
define studentC = Character("学生C")
define studentD = Character("学生D")